@startuml Answer Set Profile

sprite $EPRI [376x77/16z] {
xTm5SYH144FHVm7T_xYBmJsGktP9FP7AGEEFUePfvZewChmUGoW--Zi6yP68eMNhpdgNT_lXBJLhTrAylDSDxyhb_x0VVuQKWFVbujt7dw28kp4Ow0xS5N5t
5kFTHnzMn3sGJ7KVkolY7cW6kflT5NBNQtT5t0FHMtLHo3q38ElSprrr3_swx-gYv91UlzQuZxVTwyxvELZLmmbtuGxgSBIg1nFgpjs9kCDX04jtZViS8Dgj
--d5BdVduzthNlUwrxtkTU_sZFpkTQ-x0kxTNvKoxgyv4-SY_z7TTnoOL-Cz3dnc-NDtINdtmF7tKm13T-NT9GNTPNKtiME-Bfoykpx2NGgxA-BkFijfO8-x
A-REr5rrztHDx7LtxZQmpNrkQs1Vv3vVlO5zv_OCANS0MBhz3WDtGtZPSG92xZoQq1MizkDY07Ft_2spdaSrdAq2HDovpAhpJT_aVgfSzrSe472lEmdtkfDm
hpjrhtlTwrxtkjUzxjsEh7lTkx_wVEfkk3RSE7Tsn_0qkU0iS9__fiaukznr6tVTrPq5pnTRu3u8GDq1jhZNdRe31BOawWwGSQyxTdVg3e1_Jx7kPnXIUsoQ
vRY9EzZTMU6E_RRXmOfZJwebvdvM7XYksAKEHDYltNFspCi9WL1MuHN_1
}


footer  <$EPRI,scale=0.12,color=darkblue>  CC BY 4.0

title Responses Profile


class "ema:AnswerSet" as Anss {
    sosa:resultTime (1..1): xsd:date
}

class "ema:Answer" as Ans {
    ema:result_text : xsd:string
}
class "ema:QuestionnaireVersion" as QRV {
}

class "ema:Question" as QV {
}


class "foaf:Person" as Person

class "org:Organization" as Organization {
    ema:description : xsd:string
    ema:organizationSize : 

}

note right : "name and homepage \nattributes are confidential \ninformation. Permission needs \nto be granted by the \norganization to publish \nthis data" 

class "ema:FocusArea" as FA

enum "sgam:Zone" as iopz {
    sgam:Process 
    sgam:Field 
    sgam:Operation
    sgam:Enterprise
    sgam:Market
}

enum "sgam:Domain" as iopd {
    sgam:CustomerPremises
    sgam:DER 
    sgam:Distribution
    sgam:Transmission
    sgam:Generation
}

enum "sgam:Interoperabilitylayer" as iopl {
    sgam:ComponentLayer
    sgam:CommunicationLayer
    sgam:InformationLayer
    sgam:FunctionLayer
    sgam:BusinessLayer
    sgam:RegulatoryLayer
}

Ans --> Anss : "dcterms:isPartOf[1..1]"

Anss --> QRV : "sosa:usedProcedure [1..1]"
Ans --> QV : "sosa:usedProcedure [1..1]"

Anss --> Person :"prov:wasQuotedFrom[1..1]"
Person --> Organization : "prov:actedOnBehalfOf"

FA --> iopd : "ema:inDomain[1..*]"
FA --> iopl : "ema:onLayer[1..*]"
FA --> iopz : "ema:inZone[1..*]"
Person --> FA : "ema:AreaOfExpertise"
Organization --> FA : "ema:AreaOfOperation"

@enduml