@startuml Questionaire Profile


class "ema:QuestionnaireVersion" as QRV {
    dcterms:identifier : xsd:string
    dcat:version [1..1] : xsd:string
    skos:prefLabel : xsd:string
}

class "intnet:Question" as Q{
    dcterms:identifier [1..1] : xsd:string    
    ema:Phrasing [1..1] : xsd:string
    dcterms:identifier xsd:string
}

class "intnet:Questionnaire" as QR 




class "intnet:Dimension" as Dimension {
    
}



QR <-- QRV : "dcterms:isVersionOf"
Q <-- QRV : "dcterms:hasPart"



QRV <-- Q : "dcterms:isPartOf" 


Q --> Dimension : "ema:measures"

@enduml