@startuml Questionaire Profile


class "intnet:QuestionnaireVersion" as QRV {
    dcat:version [1..1] : xsd:string
}
class "intnet:QuestionVersion" as QV {
    dcat:version [1..1] : xsd:string
    intnet:Phrasing [1..1] : xsd:string
}
class "intnet:Question" as Q
class "intnet:Questionnaire" as QR 

class "intnet:Characteristic" as Char {
    skos:definition [1..1]
    skos:example []
}
class "intnet:Dimension" as Dimension {
    skos:definition [1..1]
}

class "intnet:Category" as Cat{
    skos:definition [1..1]
}


QR <-- QRV : "dcterms:isVersionOf"
Q <-- QRV : "dcterms:hasPart"

Q --> QV : "dcterms:hasVersion"

QR <-- Q : "dcterms:isPartOf" 

Dimension --> Cat : "dcterms:isPartOf"
Char --> Dimension : "sosa:isPropertyOf"

Q --> Char : "intnet:measures"

@enduml