@startuml Interviewing Process

sprite $EPRI [376x77/16z] {
xTm5SYH144FHVm7T_xYBmJsGktP9FP7AGEEFUePfvZewChmUGoW--Zi6yP68eMNhpdgNT_lXBJLhTrAylDSDxyhb_x0VVuQKWFVbujt7dw28kp4Ow0xS5N5t
5kFTHnzMn3sGJ7KVkolY7cW6kflT5NBNQtT5t0FHMtLHo3q38ElSprrr3_swx-gYv91UlzQuZxVTwyxvELZLmmbtuGxgSBIg1nFgpjs9kCDX04jtZViS8Dgj
--d5BdVduzthNlUwrxtkTU_sZFpkTQ-x0kxTNvKoxgyv4-SY_z7TTnoOL-Cz3dnc-NDtINdtmF7tKm13T-NT9GNTPNKtiME-Bfoykpx2NGgxA-BkFijfO8-x
A-REr5rrztHDx7LtxZQmpNrkQs1Vv3vVlO5zv_OCANS0MBhz3WDtGtZPSG92xZoQq1MizkDY07Ft_2spdaSrdAq2HDovpAhpJT_aVgfSzrSe472lEmdtkfDm
hpjrhtlTwrxtkjUzxjsEh7lTkx_wVEfkk3RSE7Tsn_0qkU0iS9__fiaukznr6tVTrPq5pnTRu3u8GDq1jhZNdRe31BOawWwGSQyxTdVg3e1_Jx7kPnXIUsoQ
vRY9EzZTMU6E_RRXmOfZJwebvdvM7XYksAKEHDYltNFspCi9WL1MuHN_1
}

footer  <$EPRI,scale=0.12,color=darkblue>  CC BY 4.0

title Interviewing Process


|Researcher|
|Interviewee|
start
|Researcher|

repeat
package explain-interview {
:Explain interviewing process;
:Explain scope of the interview;
}
|Interviewee|
repeat while (any questions) is (yes)

repeat :answer questionaire;
|Researcher|
backward :Answer questions;

|Interviewee|
repeat while (Question about questionaire?) is (yes) 

|Researcher|


|Interviewee|
:Grant or deny permission \n for privacy sensitive information \n to be used for future analysis;

|Researcher|

if (permission granted) then (yes)
:Record permission \nin metadata database;
:Record personal \ninformation to the \nmetadata database;
else (no)
:Record denied permission \nin metadata database;
endif

:Enter Metadata into \nmetadata database;
:Enter Questionaire \ninto queestionaire database;







end
@enduml