
@startuml Emininent use cases
left to right direction

title "Emininent use cases"

actor "Interoperability \nCommunity" as iopc
actor "Community Member" as cm
actor "Interviewee" as intrvw
actor "Researcher" as rsrch

package "Asses Maturity" {
    usecase "Create Maturity Report" as crmrpt
    usecase "Request Maturity\nAssesment Report" as comrpt
}
Package "Gather Data \nthrough Questionaire" {
    usecase "Take Questionaire" as tq
    usecase "Process Results" as pr

}
package "Track Maturity" {
    usecase "Create Maturity \nTracking report" as crmtrpt
    usecase "Request Maturity \nTracking report" as comtrpt
}


crmtrpt --> pr : <<include>>
crmrpt --> pr : <<include>>

intrvw -r-o cm
cm --o iopc

' "Perform Maturity Assessment" ..> "Questionaire" <<depends>>
iopc --> comrpt
iopc --> comtrpt

cm --> comrpt
cm --> comtrpt


intrvw --> tq


rsrch --> pr 
rsrch --> crmrpt
rsrch --> crmtrpt

@enduml
